### ISSUE TITLE
isp_gc1084

### ISSUE THREAD

**Issue by gokaybalci** [MuhammedKalkan/Anyka-Camera-Firmware#1]
So, I have a different camera sensor it's not isp_gc1054, but it's isp__gc1084.conf.

from this part [Creating Custom Update File](https://github.com/MuhammedKalkan/Anyka-Camera-Firmware#creating-custom-update-file)

I pulled all the related folders, added custom folder with libs and made an update.tar and successfully updated.
Web interface works and I can move the camera but rtsp doesn't work. Checked it with nmap but it only shows these ports open:

![Screenshot_20240128_125058](https://github.com/MuhammedKalkan/Anyka-Camera-Firmware/assets/51674113/1efdd5a2-78ac-4dd0-907c-6329d8217d5c)

Then I connected via telnet and gives me this one: 

`can't load library 'libplat_vi.so'`

But I have libplat_vi.so in my custom/lib folder and check the custom.sh, I have the right path:

`export LD_LIBRARY_PATH=/usr/custom/lib`

> Edit: Forgot to add that if I export path manually and try to execute rstp manually, it gives this error. I checked the other discussion posts, it happened to filder35, too. But couldn't find a solution to fix it. 

![Screenshot_20240128_125743](https://github.com/MuhammedKalkan/Anyka-Camera-Firmware/assets/51674113/6c8a48e2-47df-4eab-93a3-84a986205a2d)

What I am doing wrong? I am not an experienced user per se, so would you mind guiding me a bit to fix it myself?

Thank you in advance, başkan. 🫡

**Comment by MuhammedKalkan** [comment]
Sensor read fail might occur if you dont have drivers loaded.

Run lsmod to see isp_gc1084.ko is loaded. If not 

insmod isp_gc1084.ko

In your stock firmware /usr/modules should include those.

I suggest to try to run things manually and resolve issues. Then fix files and create a new update

**Comment by gokaybalci** [comment]
isp_gc1084.ko is not running and not in the usr/modules.

Checked my original files, it's there. Make a new update.tar with originals and flashed the update which was successful.
But after the update, it's not in modules anymore. I have to solve why it's not copying this file or deleting it.

Thank you.

**Comment by Onixaz** [comment]
Yeah exactly the same problem as I also have isp__gc1084.conf... @gokaybalci please me know if you manage to solve it. Thanks.

**Comment by gokaybalci** [comment]
I bricked my camera at the end because I packed update.tar with my rootfs instead of @MuhammedKalkan's updated version. Now camera doesn't work at all, not telnet, no wifi. Please don't make the mistake that I did, lol.

**Comment by gokaybalci** [comment]
> If it is your rootfs it should still call update first at the boot. Try to update with sdcard If it does not work Only way for you is to connect it via uart and update flash again It is recoverable

Unfortunately it doesn't do anything. When I plug the camera, I just hear a click and that's it. Trying Gerge's only SD card hack, but that doesn't do anything either. I think my rootfs had missing files and folders and fucked everything up. Even so update function doesn't work anymore.

**Comment by filder35** [comment]
The only way is to connect it via UART and read the boot log. If the camera clicks, then it works, it may be that the system has not read the files. You definitely need a log.

**Comment by filder35** [comment]
One of the options. The extension of the executable files may have changed during editing or copying. I came across this. Solution (if it is not possible to update from the SD) You need a download log, with the ability to stop the download. (this requires UART connection)

**Comment by gokaybalci** [comment]
I don't have any tools for that unfortunately. So I have to give up here. Thank you all.

**Comment by filder35** [comment]
And one more piece of advice from personal experience on camera modification. Whenever I made changes to the firmware, I always checked for file extensions with which I was working (user group affiliation and especially launch scripts for the right to launch). And just to be sure, I ran three commands:
sudo chown -R root /(location of the directory in which changes were made)
sudo chgrp -R root /(location of the directory in which changes were made)
chmod +x -R /(location of the directory in which changes were made)

**Comment by MuhammedKalkan** [comment]
> I don't have any tools for that unfortunately. So I have to give up here. Thank you all.

If you have means to deliver it, i can take a look at that for you

**Comment by gokaybalci** [comment]
> > I don't have any tools for that unfortunately. So I have to give up here. Thank you all.
> 
> If you have means to deliver it, i can take a look at that for you

Of course. I bought this camera just to watch my dog when I am at work, and I broke my leg so I am home for a month anyways, lol. So take your time. You can e-mail me your address and I will send it you.

**Comment by MuhammedKalkan** [comment]
> Yeah exactly the same problem as I also have isp__gc1084.conf... @gokaybalci please me know if you manage to solve it. Thanks.

There is a sd card only method available. Try that and look into logs for errors

**Comment by Onixaz** [comment]
@MuhammedKalkan I see, we'll try that. Just I'd need to revert back the changes I assume ? Any guidance how you do that ?

**Comment by Onixaz** [comment]
Same problem. I tried to launch rtsp manually, but this is what I get:

`
[root@anyka /mnt/Factory/custom]$ ./rtsp
default log level=4
[ak_vi_match_sensor:849] config_file: /etc/jffs2/

[check_data:225] /etc/jffs2/isp_gc1084.conf is not need file!
[check_data:227] sensor_id:0x0, 0x1084, style_id:0, 0
[check_file:338] read sensor fail

[ak_rtsp_vi_init:150] match sensor failed

vi init fail
`

**Comment by MuhammedKalkan** [comment]
Send your original usr and etc/init.d , etc/jffs2 folders

**Comment by Onixaz** [comment]
Ah sadly Github won't let me post bigger zip then 25mb. Regarding the sensor_gc1084.ko, that file after the update dissapeared from /usr/modules. Just like for @gokaybalci , Even though its there in my original usr/modules. 

Anyways, let me find some file sharing service to send you my originals.

**Comment by MuhammedKalkan** [comment]
Maybe i should have pointed out this section more

https://github.com/MuhammedKalkan/Anyka-Camera-Firmware?tab=readme-ov-file#different-hardware

**Comment by filder35** [comment]
For 7 days, both Sensor gc_1054 and sc_1345 cameras have been working non-stop until I observed any errors. Now I want to experiment with ONVIF and I want to upgrade the web server to output the RTSP stream (I can’t connect the DVR yet)

**Comment by filder35** [comment]
And another option. When I started experimenting with the demo, I also encountered a problem with the sensor config. The solution was this: I indicated in the source code the exact location of the configuration file and its exact name, and this helped me.

**Comment by filder35** [comment]
> Ах, к сожалению, Github не позволяет мне публиковать zip-файлы размером больше 25 МБ. Что касается Sensor_gc1084.ko, то этот файл после обновления исчез из /usr/modules. Точно так же, как для@gokaybalci, Хотя он есть в моих исходных файлах usr/modules.
> 
> В любом случае, позвольте мне найти какой-нибудь файлообменник, чтобы отправить вам мои оригиналы.
your file Sensor_gc1084.ko in theory should have been in the file being updated usr.sqsh4, if it was not in the update file then where will it come from? And the original is erased.
Post here your file with which you updated usr.sqsh4.
Or you can unzip it yourself with the command
unsquashfs -d usr_out usr.sqsh4
and see if the driver for the existing module is available.

**Comment by Onixaz** [comment]
@filder35 Thing is I used the precompiled binaries and the updater.tar provided in in this repo.  Had no idea this sensor_1084.ko wasn't part of the release. Yeah ill try to make my own updater.

**Comment by filder35** [comment]
The cameras on this processor are varied. Therefore, you need to be careful about updating actions. Muhammed Kalkan put together some great code. But that was the equipment that was available. The operating algorithms for these cameras are the same. Various sensors and wifi. Therefore, you need to be careful about this. At the bottom of the repository page there are links where you can read how it started and what actions were taken.

**Comment by MuhammedKalkan** [comment]
I got your files. If they are really original ones, O believe only missing file is sensor_gc1084.ko. 

I have added your files and released a new version. Please try that. It should just work

https://github.com/MuhammedKalkan/Anyka-Camera-Firmware/releases/tag/1.0.3

**Comment by MuhammedKalkan** [comment]
> For 7 days, both Sensor gc_1054 and sc_1345 cameras have been working non-stop until I observed any errors. Now I want to experiment with ONVIF and I want to upgrade the web server to output the RTSP stream (I can’t connect to the DVR yet)

Lets use discussions if you feel like it
