### ISSUE TITLE
onvif binary missing from file system

### ISSUE THREAD

**Issue by IanDGibbons** [MuhammedKalkan/Anyka-Camera-Firmware#15]
Issue: The onvif file is not present on the file system after update. 

I followed the instructions and succesfully updated the camera firmware.  I can view RTSP streams and control the camera via wen interface on port 8080.  I have root access via telentd.

This camera is an unbranded 'Wifi Smart Camera' that suggest you use the YI IOT app - which it works fine with.  It appears identical to the YI IOT Outdoor 1080p camera.

**Comment by MuhammedKalkan** [comment]
There is not enough room on flash to fit everything. Try sd card method. 

Also i do not recommend onvif. It is just video stream

**Comment by MuhammedKalkan** [comment]
If you can set Rest methods on zoneminder, that d be a trivial thing to achieve
